yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main_page'),
    path('group/<slug:slug>/',
         views.group_posts,
         name='groups'),
    path('profile/<str:username>/',
         views.profile,
         name='profile'),
    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'),
    path('create/',
         views.post_create,
         name='post_create'),
    path('posts/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler403 = 'core.views.permission_denied_view'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from core.models import PubDateModel


User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название'
    )
    slug = models.SlugField(
        max_length=100,
        verbose_name='Уникальный Идентификатор',
        unique=True
    )
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(PubDateModel):
    text = models.TextField(
        verbose_name='Текст Поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts',
        null=True
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Группа',
        related_name='posts'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(PubDateModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор Комментария'
    )
    text = models.TextField(
        verbose_name='Текст Комментария'
    )

    class Meta:
        ordering = ('pub_date',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        get_latest_by = 'pub_date'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'Подписка',
        verbose_name_plural = 'Подписки'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)
        labels = {
            'text': ('Текст поста'),
            'group': ('Группа'),
            'image': ('Картинка'),
        }
        help_texts = {
            'text': ('Текст нового поста'),
            'group': ('Группа, к которой будет относиться пост'),
            'image': ('Картинка к посту'),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': ('Текст Комментария'), }
        help_texts = {'text': ('Напишите текст комментария'), }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .models import Group, Post, Follow, User
from .forms import PostForm, CommentForm
from yatube.settings import PROFILE_POSTS, POSTS


def paginate(queryset, request, page_size=POSTS):
    return Paginator(queryset, page_size).get_page(request.GET.get('page'))


def index(request):
    return render(request, 'posts/index.html', {
        'page_obj': paginate(Post.objects.all(), request),
    })


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    return render(request, 'posts/group_list.html', {
        'group': group,
        'page_obj': paginate(group.posts.all(), request),
    })


def profile(request, username):
    author = get_object_or_404(User, username=username)
    if request.user.is_authenticated:
        Follow.objects.filter(user=request.user, author=author).exists()
    return render(request, 'posts/profile.html', {
        'author': author,
        'page_obj': paginate(author.posts.all(), request, PROFILE_POSTS),
        'following': Follow.objects.all(),
    })


def post_detail(request, post_id, form=None):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'posts/post_detail.html', {
        'post': post,
        'form': CommentForm(request.POST or None),
        'switched_to_post_detail': True
    })


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None,)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('posts:profile', post.author)
    return render(request, 'posts/create_post.html', {
        'form': form,
    })


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html', {
        'form': form,
        'is_edit': True,
    })


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    return render(request, 'posts/follow.html', {
        'page_obj': paginate(Post.objects.all().filter(
            author__following__user=request.user), request),
    })


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user and not author.following.filter(
        user=request.user,
    ).exists():
        Follow.objects.create(
            user=request.user,
            author=author,
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(request.user.follower,
                      author__username=username).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  {% if is_edit %}Редактировать Пост{% else %}Новый Пост{% endif %}
{% endblock %}
{% block content %}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-body">
              <form method="post" enctype="multipart/form-data">
                <div class="card-header">
                  {% if is_edit %}Редактировать пост{% else %}Добавить пост{% endif %}
                </div>
                {% csrf_token %}
                {% for field in form %}
                  <div class="fieldWrapper">
                    <div class="form-group row my-3 p-3">
                      {{ field.errors }}
                      {{ field.label_tag }}{% if field.field.required %}<span class="text-danger">*</span>{% endif %}
                      {{ field }}
                      {% if field.help_text %}
                        <small class="help form-text text-muted">{{ field.help_text|safe }}</small>
                      {% endif %}
                    </div>
                  </div>
                {% endfor %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}Сохранить{% else %}Добавить{% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Последние записи избранных авторов{% endblock %}
{% block content %}
  <div class="container">
    {% include 'includes/switcher.html' with follow=True %}
    <h1>Последние записи избранных авторов на сайте</h1>
    {% if not page_obj %}
      <h2>Нет записей</h2>
      <p>Подпишитесь на интересных вам авторов чтобы следить за их новыми записями на этой странице.</p>
    {% endif %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_item.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}Записи группы {{ group.title }}{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
  <div class="container">
    <p>{{ group.description|linebreaksbr }}</p>
    {% for post in page_obj %}
      {% include 'posts/includes/post_item.html' with hide_group=True %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% load cache %}
{% block title %}Yatube{% endblock %}
{% block header %}Последние обновления{% endblock %}
{% block content %}
  {% cache 20 index_page %}
    <div class="container">
      {% for post in page_obj %}
        {% include 'posts/includes/post_item.html' %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'includes/paginator.html' %}
    </div>
  {% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}Пост: {{ post.text|truncatewords:30 }}{% endblock %}
{% block header %}Детали поста:{% endblock %}
{% block content %}
  <div class="row">
    {% include 'posts/includes/post_item.html' %}
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}
  Профайл пользователя: {{ author.get_full_name }}
{% endblock %}
{% block header %}Все посты пользователя: {{ author.get_full_name }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h3>Всего постов: {{ author.posts.count }}<br>
    Подписчиков: {{ author.following.count }}<br>
    Подписок: {{ author.follower.count }}</h3>
    {% if author != user and user.is_authenticated %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >Отписаться</a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >Подписаться</a>
      {% endif %}
    {% endif %}
    {% for post in page_obj %}   
      {% include 'posts/includes/post_item.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}